name: $name
version: $version
main: $group.${name}Plugin
description: $description
author: Hydrolien
website: https://github.com/HydrolienF/${name}
api-version: "$apiVersion"
folia-supported: true
permissions:
  minecraftssh:
    description: "Allows use of commands."
    default: op